FROM node:22.11.0-alpine

# Update the package index and install tzdata for time zone data
RUN apk update && apk add --no-cache 

ENV TZ=Asia/Kuala_Lumpur 

COPY ./ /app

WORKDIR /app

# Install the project dependencies
RUN npm install

RUN npm run build

# Create necessary directories and set permissions
RUN mkdir -p /app/logs \
    && mkdir -p /app/temp \
    && mkdir -p /app/logs/applications \
    && mkdir -p /app/logs/exceptions \
    && mkdir -p /app/logs/errors \
    && chmod -R 777 /app/logs \
    && chmod -R 777 /app/temp\
    && chmod -R 777 /app/migrations

#ENV NODE_ENV production

EXPOSE 8080

CMD ["node", "dist/src/main.js"]
